spring:
  profiles:
    active: prod
 
  datasource:
    hikari:
      read-only: false #连接只读数据库时配置为true， 保证安全 
      connectionTimeout: 30000 # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 缺省:30秒
      idleTimeout: 600000 #一个连接idle状态的最大时长（毫秒），超时则被释放（retired），缺省:10分钟
      maxLifetime: 1765000 #一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒以上
      maximumPoolSize: 15 #连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)

  devtools:
    restart:
      exclude: static/**,public/**
 
# 配置mybatis-plus
mybatis-plus:
  # 配置扫描xml
  mapper-locations: classpath:mappings/**/*.xml
  # 实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: cn.leap.demo.modules.*.model
  global-config:
    # 逻辑删除配置
    logic-delete-value: 0
    logic-not-delete-value: 1
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector

# 分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
  
---
# 开发环境配置
spring:
  profiles: dev
  
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/
    driver-class-name: com.mysql.jdbc.Driver

server:
  port: 8080
 
---
# 测试环境配置
spring:
  profiles: test
  
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/
    driver-class-name: com.mysql.jdbc.Driver
    
server:
  port: 8080
  
---
# 生产环境配置
spring:
  profiles: prod
  
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/iottest?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    
server:
  port: 80

---